"""Indicator catalogue tests.

The catalogue is generated by backend/app/charts/gen_indicator_catalogue.mjs from
the browser's indicator registry and read by load_catalogue() in
backend/app/tools/charts.py. Three things can rot, and each is asserted here from
the files as text, without node:

  - The shape. The tool layer keys on id, name, category, placement, inputs,
    numeric_keys and plots, and the expressiveness work added style_inputs, fill
    and fills. Every entry must carry all of them, and style keys must be unique
    per indicator because a settings dict has one slot per key.
  - The engine. chart_engine_version must be the openalgo-charts installed under
    frontend/node_modules, or the catalogue was not regenerated after an upgrade.
  - The bollinger patch. The browser registers a fillColor input and a fill over
    the built-in (frontend/src/lib/charts/indicatorOverrides.ts) and the generator
    applies the same patch before dumping. The BOLLINGER_* constants are read out
    of both source files by name and compared with each other and with the JSON,
    so a change on one side fails here rather than in a user's prompt.

Run:  python backend/tests/test_catalogue.py
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
CATALOGUE = ROOT / "backend" / "app" / "charts" / "indicator_catalogue.json"
GENERATOR = ROOT / "backend" / "app" / "charts" / "gen_indicator_catalogue.mjs"
OVERRIDES = ROOT / "frontend" / "src" / "lib" / "charts" / "indicatorOverrides.ts"
PACKAGE = ROOT / "frontend" / "node_modules" / "openalgo-charts" / "package.json"

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

PASS, FAIL, SKIP = "PASS", "FAIL", "SKIP"
results: list[tuple[str, str]] = []

# What charts.py read before this work, and what it gained. Both sets are required.
LEGACY_KEYS = ("id", "name", "category", "placement", "inputs", "numeric_keys", "plots")
ADDED_KEYS = ("style_inputs", "fill", "fills")
FILL_KEYS = ("has", "color_key", "opacity")
FILLS_ENTRY_KEYS = ("between", "color_up_key", "color_down_key", "opacity")
# indicatorStyleInputs derives these four per plot in 1.9.2.
PLOT_STYLE_SUFFIXES = ("opacity", "width", "lineStyle", "type")
# The constants both the generator and the browser override declare by this name.
SHARED_CONSTANTS = (
    "BOLLINGER_ID",
    "BOLLINGER_FILL_KEY",
    "BOLLINGER_FILL_LABEL",
    "BOLLINGER_FILL_OPACITY",
    "BOLLINGER_FILL_BETWEEN",
)
# The upper/basis/lower indicators. All of them shade once bollinger is patched.
BAND_INDICATORS = (
    "bollinger",
    "envelope",
    "donchian",
    "keltner-channel",
    "ma-channel",
    "standard-error-bands",
)

# `export const NAME = <json literal> as const;` in TS, `const NAME = <json literal>;`
# in the .mjs. The literal is captured as JSON, which both languages share for
# strings, numbers and arrays of strings.
_CONST_RE = r"^\s*(?:export\s+)?const\s+{name}\s*=\s*(.*?)(?:\s+as\s+const)?\s*;?\s*$"


def check(name: str, condition: bool, detail: str = "") -> None:
    status = PASS if condition else FAIL
    results.append((name, status))
    print(f"  [{status}] {name}" + (f" - {detail}" if detail else ""))


def skip(name: str, detail: str = "") -> None:
    results.append((name, SKIP))
    print(f"  [{SKIP}] {name}" + (f" - {detail}" if detail else ""))


def read_constants(path: Path) -> dict[str, Any]:
    """Pull the shared constants out of a JS or TS source as JSON values.

    Args:
        path: The generator or the override module.

    Returns:
        Name to parsed value for every constant found. A constant whose literal is
        not JSON is recorded as None so the comparison fails loudly.
    """
    source = path.read_text(encoding="utf-8")
    found: dict[str, Any] = {}
    for name in SHARED_CONSTANTS:
        match = re.search(_CONST_RE.format(name=name), source, re.MULTILINE)
        if not match:
            continue
        try:
            found[name] = json.loads(match.group(1))
        except ValueError:
            found[name] = None
    return found


def test_shape(cat: dict[str, Any]) -> None:
    print("\n--- shape ---")
    top = ("generated_by", "chart_engine", "chart_engine_version", "count", "chart_types", "indicators")
    check("top-level keys", all(k in cat for k in top), ", ".join(k for k in top if k not in cat))
    inds: dict[str, dict[str, Any]] = cat["indicators"]
    check("count matches the entries", cat["count"] == len(inds), f"{cat['count']} vs {len(inds)}")
    check("the full 1.9.2 registry", len(inds) >= 102, str(len(inds)))
    check("ids match their keys", all(e["id"] == i for i, e in inds.items()))

    missing_legacy = [i for i, e in inds.items() if any(k not in e for k in LEGACY_KEYS)]
    check("every entry keeps the legacy keys", not missing_legacy, ", ".join(missing_legacy[:6]))
    missing_added = [i for i, e in inds.items() if any(k not in e for k in ADDED_KEYS)]
    check("every entry has style_inputs, fill and fills", not missing_added, ", ".join(missing_added[:6]))
    bad_fill = [i for i, e in inds.items() if set(e["fill"]) != set(FILL_KEYS)]
    check("fill has exactly has, color_key, opacity", not bad_fill, ", ".join(bad_fill[:6]))
    bad_entries = [
        i
        for i, e in inds.items()
        for f in e["fills"]
        if set(f) != set(FILLS_ENTRY_KEYS) or len(f["between"]) != 2
    ]
    check("fills entries have between, color_up_key, color_down_key, opacity", not bad_entries)

    dup = [i for i, e in inds.items() if len({s["key"] for s in e["style_inputs"]}) != len(e["style_inputs"])]
    check("style keys are unique per indicator", not dup, ", ".join(dup[:6]))
    shapeless = [
        i
        for i, e in inds.items()
        if any(not all(k in s for k in ("key", "type", "label")) for s in e["style_inputs"])
    ]
    check("every style input has key, type and label", not shapeless, ", ".join(shapeless[:6]))
    lacking: list[str] = []
    for i, e in inds.items():
        keys = {s["key"] for s in e["style_inputs"]}
        lacking.extend(
            f"{i}.{p}:{suffix}" for p in e["plots"] for suffix in PLOT_STYLE_SUFFIXES if f"{p}:{suffix}" not in keys
        )
    check("every plot has opacity, width, lineStyle and type", not lacking, ", ".join(lacking[:6]))
    bad_scale = [
        f"{i}.{s['key']}"
        for i, e in inds.items()
        for s in e["style_inputs"]
        if s["key"].endswith(":opacity") and (s.get("min") != 0 or s.get("max") != 100)
    ]
    check("plot opacity is a 0..100 percentage", not bad_scale, ", ".join(bad_scale[:6]))

    inconsistent = [i for i, e in inds.items() if e["fill"]["has"] != bool(e["fills"])]
    check("fill.has agrees with fills", not inconsistent, ", ".join(inconsistent[:6]))
    dangling: list[str] = []
    for i, e in inds.items():
        colour_key = e["fill"]["color_key"]
        if colour_key is None:
            continue
        inputs = {inp["key"]: inp for inp in e["inputs"]}
        if colour_key not in inputs or inputs[colour_key]["type"] != "color":
            dangling.append(f"{i}:{colour_key}")
    check("fill.color_key names a colour input of its indicator", not dangling, ", ".join(dangling[:6]))
    bad_opacity = [
        i for i, e in inds.items() if e["fill"]["opacity"] is not None and not 0 < e["fill"]["opacity"] <= 1
    ]
    check("fill.opacity sits within 0..1", not bad_opacity, ", ".join(bad_opacity[:6]))
    # Measured on 1.9.2: 28 built-ins declare fills, and the bollinger patch makes 29.
    shaded = sum(1 for e in inds.values() if e["fill"]["has"])
    check("the 28 shading built-ins plus bollinger", shaded >= 29, f"{shaded} of {len(inds)}")


def test_engine(cat: dict[str, Any]) -> None:
    print("\n--- engine ---")
    check("engine is openalgo-charts", cat["chart_engine"] == "openalgo-charts", str(cat["chart_engine"]))
    check(
        "generated_by names the generator",
        cat["generated_by"] == "backend/app/charts/gen_indicator_catalogue.mjs",
        str(cat["generated_by"]),
    )
    if PACKAGE.exists():
        installed = json.loads(PACKAGE.read_text(encoding="utf-8"))["version"]
        check(
            "catalogue matches the installed engine",
            cat["chart_engine_version"] == installed,
            f"catalogue {cat['chart_engine_version']}, installed {installed}",
        )
    else:
        skip("catalogue matches the installed engine", "frontend/node_modules is absent")


def test_measured_entries(cat: dict[str, Any]) -> None:
    print("\n--- measured entries ---")
    inds = cat["indicators"]
    keltner = inds["keltner-channel"]["fill"]
    check(
        "keltner shades from fillColor at 0.05",
        keltner == {"has": True, "color_key": "fillColor", "opacity": 0.05},
        str(keltner),
    )
    sma = inds["sma"]
    check("sma has no fill", sma["fill"] == {"has": False, "color_key": None, "opacity": None}, str(sma["fill"]))
    sma_keys = {s["key"] for s in sma["style_inputs"]}
    check(
        "sma style keys are its colour plus the four plot keys",
        sma_keys == {"color", "ma:opacity", "ma:width", "ma:lineStyle", "ma:type"},
        ", ".join(sorted(sma_keys)),
    )
    unshaded = [i for i in BAND_INDICATORS if not inds[i]["fill"]["has"]]
    check("every band indicator shades", not unshaded, ", ".join(unshaded))
    off_key = [i for i in BAND_INDICATORS if inds[i]["fill"]["color_key"] != "fillColor"]
    check("every band indicator shades from fillColor", not off_key, ", ".join(off_key))


def test_bollinger_patch(cat: dict[str, Any]) -> None:
    print("\n--- bollinger patch ---")
    gen = read_constants(GENERATOR)
    over = read_constants(OVERRIDES)
    check(
        "generator declares every shared constant",
        set(gen) == set(SHARED_CONSTANTS),
        ", ".join(sorted(set(SHARED_CONSTANTS) - set(gen))),
    )
    check(
        "override declares every shared constant",
        set(over) == set(SHARED_CONSTANTS),
        ", ".join(sorted(set(SHARED_CONSTANTS) - set(over))),
    )
    drift = [n for n in SHARED_CONSTANTS if gen.get(n) != over.get(n) or gen.get(n) is None]
    check("generator and override agree", not drift, ", ".join(drift))
    check("override names the generator", "gen_indicator_catalogue.mjs" in OVERRIDES.read_text(encoding="utf-8"))
    check("generator names the override", "indicatorOverrides.ts" in GENERATOR.read_text(encoding="utf-8"))

    fill_key = gen.get("BOLLINGER_FILL_KEY") or "fillColor"
    bollinger = cat["indicators"][gen.get("BOLLINGER_ID") or "bollinger"]
    inputs = {i["key"]: i for i in bollinger["inputs"]}
    band = inputs.get("bandColor")
    fill_input = inputs.get(fill_key)
    check("bollinger advertises the fill input", fill_input is not None, ", ".join(inputs))
    if fill_input is not None and band is not None:
        check("fill input is a colour", fill_input["type"] == "color", str(fill_input["type"]))
        check("fill input label", fill_input["label"] == gen.get("BOLLINGER_FILL_LABEL"), str(fill_input["label"]))
        check("fill default is the band default", fill_input["default"] == band["default"], str(fill_input["default"]))
        check("fill input comes after the built-ins", bollinger["inputs"][-1]["key"] == fill_key)
    fill = bollinger["fill"]
    check("fill.has is true", fill["has"] is True, str(fill))
    check("fill.color_key is the fill input", fill["color_key"] == fill_key, str(fill))
    check("fill.opacity is the shared constant", fill["opacity"] == gen.get("BOLLINGER_FILL_OPACITY"), str(fill))
    between = bollinger["fills"][0]["between"] if bollinger["fills"] else None
    check("fills[0].between is the shared constant", between == gen.get("BOLLINGER_FILL_BETWEEN"), str(between))
    check("numeric keys untouched", bollinger["numeric_keys"] == ["length", "stdDev"], str(bollinger["numeric_keys"]))
    check("plots untouched", bollinger["plots"] == ["upper", "basis", "lower"], str(bollinger["plots"]))
    style_keys = {s["key"] for s in bollinger["style_inputs"]}
    check(
        "per-plot style keys survive the patch",
        {"upper:opacity", "basis:opacity", "lower:opacity", "bandColor", "basisColor"} <= style_keys,
        ", ".join(sorted(style_keys)),
    )


def main() -> int:
    try:
        cat = json.loads(CATALOGUE.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        print(f"  [{FAIL}] catalogue unreadable at {CATALOGUE}: {exc}")
        return 1

    test_shape(cat)
    test_engine(cat)
    test_measured_entries(cat)
    test_bollinger_patch(cat)

    n_pass = sum(1 for _, s in results if s == PASS)
    n_fail = sum(1 for _, s in results if s == FAIL)
    n_skip = sum(1 for _, s in results if s == SKIP)
    print("\n=== Summary ===")
    for name, status in results:
        if status == FAIL:
            print(f"  FAILED: {name}")
    print(f"  {n_pass} passed, {n_fail} failed, {n_skip} skipped")
    return 1 if n_fail else 0


if __name__ == "__main__":
    raise SystemExit(main())
